version: '3'
services:
  php:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8080:80
    restart: always
    command: 'composer startup'
    